[de]
    title = "Darkbrightness"
    languagename = "deutsch"
    weight = 1
[de.params]
    subtitle = "Alles rund ums Thema Horror"

# Test Language variables
[en]
    title = "My blog"
    languagename = "english"
    weight = 2
[fr]
    title = "Mon blogue"
    languagename = "français"
    weight = 3