# Note: [[]] is an array of tables
# Note: [] is a table in TOML

[[main]]
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    name = "Posts"
    url = "/posts"
    weight = 2

[[main]]
    name = "Kategorien"
    url = "/categories"
    weight = 3

[[main]]
    name = "Tags"
    url = "/tags"
    weight = 4